services:
  mysqldb:
    image: mysql:8.0
    container_name: mysqldb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: voiture_db
      # MYSQL_USER: root
      # MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - ensa

  adminer:
    image: adminer
    container_name: adminer
    environment:
      - ADMINER_DESIGN=dracula
    ports:
      - "8888:8080"
    networks:
      - ensa
    restart: always
    init: true

  front:
    build: 
      context: ./front
      dockerfile: Dockerfile
    container_name: ensafront
    ports:
      - '4200:4200'
    depends_on:
      - mysqldb
    restart: unless-stopped
    volumes:
      - ./front:/app/
      - ensa_front_modules:/app/node_modules
    networks:
      - ensa

  back:
    build: 
      context: ./back
      dockerfile: Dockerfile
    container_name: ensaback
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DEVTOOLS_RESTART_ENABLED=true
    ports:
      - '8080:8080'
    depends_on:
      - mysqldb
    restart: unless-stopped
    volumes:
      - ./back:/app/
      - ./back/target:/app/target
    networks:
      - ensa

  watch:
    image: eclipse-temurin:21
    container_name: watch
    working_dir: /app
    volumes:
      - .:/app
    command: ["./mvnw", "compile", "-Dwatch"]
    networks:
      - ensa
    
volumes:
  dbdata:
  ensa_front_modules:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./front/node_modules

networks:
  ensa:
